-- Generated by scripts/generate-seed.mjs — DO NOT EDIT BY HAND.
--
-- LOCAL DEVELOPMENT ONLY. The imagery here is placeholder stock photography from
-- the fixtures and some of it shows other makers' trademarked product, so this
-- must never reach a production database. Replaced at Phase F by real
-- photography, at which point regenerate rather than editing.
--
-- Mirrors app/utils/mock/{products,rates,announcements}.ts so the Phase F swap
-- from fixtures to Supabase is invisible. Regenerate with:
--     npm run db:seed:generate
--
-- Deliberate holes preserved from the fixtures, because each one makes a real
-- code path reachable against the real database rather than only against mocks:
--   · Zamfara has no delivery_rates row at all  -> unpriced destination, null fee
--   · Bayelsa has a row but active = false      -> same path, different cause
--   · two pieces are out of stock               -> the sold_out raise
--   · two sit at stock_count = 2                -> the "2 left" low-stock badge
--   · three are made_to_order                   -> exempt from the sold_out check
--
-- Idempotent: every insert is ON CONFLICT DO NOTHING, and ids are deterministic
-- (md5 of a stable key), so re-running never duplicates or reshuffles a row.

-- 28 pieces across all five categories.
insert into public.products
  (id, slug, name, brand, description, category, price_ngn, compare_at_ngn,
   images, specs, tags, in_stock, stock_count, made_to_order, featured, created_at)
values
  ('e38265ce-8879-4892-84f2-1a86e1307fde', 'meridian-automatic-40', 'Meridian Automatic 40', 'Meridian', 'A 40mm automatic with a sector dial and a movement worth servicing thirty years from now. Worn thin under a cuff, heavy enough to notice.', 'watches', 1850000, NULL, array['https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic · 38h reserve"},{"label":"Case","value":"40mm stainless steel"},{"label":"Crystal","value":"Sapphire, anti-reflective"},{"label":"Water resistance","value":"50m"}]'::jsonb, array['new']::text[], true, NULL, false, true, '2026-09-12T09:00:00Z'),
  ('6e83221b-2272-4c93-a44d-f4423cd28d02', 'meridian-chronograph', 'Meridian Chronograph', 'Meridian', 'Three registers, a column wheel, and a pusher action that feels mechanical because it is. The dial darkens toward the edge.', 'watches', 2450000, 2780000, array['https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic chronograph · 48h"},{"label":"Case","value":"41mm stainless steel"},{"label":"Crystal","value":"Sapphire, double-domed"},{"label":"Water resistance","value":"100m"}]'::jsonb, array['limited']::text[], true, NULL, false, false, '2026-08-30T09:00:00Z'),
  ('adaf48ce-5efc-4335-8bdc-87b60f9b848c', 'aster-field-38', 'Aster Field 38', 'Aster', 'The watch you stop thinking about. 38mm, legible at a glance, light enough to sleep in.', 'watches', 980000, NULL, array['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic · 41h reserve"},{"label":"Case","value":"38mm brushed steel"},{"label":"Crystal","value":"Sapphire"},{"label":"Water resistance","value":"100m"}]'::jsonb, array['everyday', 'new']::text[], true, NULL, false, false, '2026-09-20T09:00:00Z'),
  ('131945fd-6a11-410c-bfde-ee78fc085438', 'abyss-diver-300', 'Abyss Diver 300', 'Abyss', 'Rated to 300m and built like it. Ceramic bezel, lumed to read at depth, on a bracelet that tapers properly.', 'watches', 1650000, NULL, array['https://images.unsplash.com/photo-1548171915-e79a380a2a4b?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic · 70h reserve"},{"label":"Case","value":"42mm steel, ceramic bezel"},{"label":"Crystal","value":"Sapphire, AR-coated"},{"label":"Water resistance","value":"300m"}]'::jsonb, array[]::text[], true, NULL, false, true, '2026-07-18T09:00:00Z'),
  ('2b5cecc0-fe53-4f28-a078-622819f27650', 'noir-automatic', 'Noir Automatic', 'Meridian', 'Black on black, with only the hands catching light. A dress watch for people who dislike dress watches.', 'watches', 1320000, NULL, array['https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic · 42h reserve"},{"label":"Case","value":"39mm blackened steel"},{"label":"Crystal","value":"Sapphire"},{"label":"Water resistance","value":"30m"}]'::jsonb, array[]::text[], true, NULL, false, false, '2026-06-04T09:00:00Z'),
  ('c8638cfc-5aec-48c4-b4cf-c18f1f108f36', 'obsidian-gmt', 'Obsidian GMT', 'Obsidian', 'A second time zone on a fourth hand, for the version of you that keeps Lagos and London in the same glance.', 'watches', 2150000, NULL, array['https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic GMT · 72h"},{"label":"Case","value":"40mm steel"},{"label":"Crystal","value":"Sapphire"},{"label":"Water resistance","value":"100m"}]'::jsonb, array['limited']::text[], true, 2, false, true, '2026-09-02T09:00:00Z'),
  ('c1275b56-50b6-4018-ab75-4c82a2dc879a', 'heirloom-pocket', 'Heirloom Pocket Watch', 'Heirloom', 'Hand-wound, open-faced, engraved to order. Made after you ask for it, which is the only honest way to sell one.', 'watches', 740000, NULL, array['https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Hand-wound · 44h reserve"},{"label":"Case","value":"48mm sterling silver"},{"label":"Crystal","value":"Mineral"},{"label":"Water resistance","value":"Not rated"}]'::jsonb, array['limited', 'gift']::text[], true, NULL, true, false, '2026-05-21T09:00:00Z'),
  ('03e88aec-25ff-4241-953a-6a8f48ec9969', 'steel-sport-diver', 'Steel Sport Diver', 'Abyss', 'The bracelet version of the Abyss, in a smaller case. Sold out; the next run lands in the new year.', 'watches', 1450000, NULL, array['https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Movement","value":"Automatic · 50h reserve"},{"label":"Case","value":"39mm steel"},{"label":"Crystal","value":"Sapphire"},{"label":"Water resistance","value":"200m"}]'::jsonb, array[]::text[], false, NULL, false, false, '2026-04-11T09:00:00Z'),
  ('91c8cbfc-327e-423c-9bdd-5da8b5ead71c', 'solitaire-halo-ring', 'Solitaire Halo Ring', 'Atelier JB', 'A brilliant-cut moissanite held in a halo that does the work of a larger stone. Graded on the same scale as diamond.', 'rings', 1200000, NULL, array['https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1608042314453-ae338d80c427?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"2.0ct moissanite · D–F"},{"label":"Metal","value":"18k white gold"},{"label":"Setting","value":"Four-prong halo"},{"label":"Band","value":"2.2mm, pavé shoulders"}]'::jsonb, array['moissanite', 'new']::text[], true, NULL, false, true, '2026-09-16T09:00:00Z'),
  ('a5b1d9b1-1fda-4d8f-9ccc-670a93d0da2f', 'rose-sapphire-halo', 'Rose Sapphire Halo', 'Atelier JB', 'A cushion-cut pink sapphire in rose gold, warm against most skin tones and unmistakable across a room.', 'rings', 860000, NULL, array['https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1608042314453-ae338d80c427?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"1.4ct pink sapphire"},{"label":"Metal","value":"18k rose gold"},{"label":"Setting","value":"Cushion halo"},{"label":"Band","value":"2.0mm, tapered"}]'::jsonb, array[]::text[], true, NULL, false, false, '2026-08-08T09:00:00Z'),
  ('9a302fe5-fbbe-44ed-8464-532bf2f5163a', 'stacking-band-trio', 'Stacking Band Trio', 'Aster', 'Three bands, worn together or apart. The set that survives being worn every day for a decade.', 'rings', 420000, NULL, array['https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1608042314453-ae338d80c427?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"None"},{"label":"Metal","value":"18k yellow gold"},{"label":"Setting","value":"Plain, polished"},{"label":"Band","value":"1.4mm × 3"}]'::jsonb, array['everyday', 'gift']::text[], true, NULL, false, false, '2026-09-24T09:00:00Z'),
  ('cccaca4d-aaf8-41cf-9ebc-500b03813ef1', 'cabochon-signet', 'Cabochon Signet', 'Heirloom', 'A signet with a domed stone instead of an engraving. Quieter than a crest, and harder to place.', 'rings', 380000, NULL, array['https://images.unsplash.com/photo-1608042314453-ae338d80c427?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Onyx cabochon"},{"label":"Metal","value":"14k yellow gold"},{"label":"Setting","value":"Bezel"},{"label":"Band","value":"3.0mm signet"}]'::jsonb, array['statement']::text[], true, NULL, false, false, '2026-07-02T09:00:00Z'),
  ('4476d6a6-1861-4738-96a5-242617896fa2', 'aurora-cluster-ring', 'Aurora Cluster Ring', 'Atelier JB', 'Seven moissanite stones set close so the fire reads as one surface. Built to your size after you order.', 'rings', 690000, NULL, array['https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"7 × 0.3ct moissanite"},{"label":"Metal","value":"18k white gold"},{"label":"Setting","value":"Cluster, shared prong"},{"label":"Band","value":"1.8mm"}]'::jsonb, array['moissanite']::text[], true, NULL, true, false, '2026-06-19T09:00:00Z'),
  ('c5a14be3-fb40-49a3-ac84-30c68235a6a7', 'pearl-strand', 'Akoya Pearl Strand', 'Heirloom', 'Forty-two hand-knotted Akoya pearls, matched for lustre rather than size. The gift that is never wrong.', 'necklaces', 520000, NULL, array['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Akoya pearl · 7.5mm"},{"label":"Metal","value":"14k gold clasp"},{"label":"Length","value":"45cm"},{"label":"Clasp","value":"Hidden box"}]'::jsonb, array['gift']::text[], true, NULL, false, false, '2026-08-14T09:00:00Z'),
  ('308c4c91-0208-4511-8b39-9adb76a34a25', 'azure-pendant', 'Azure Pendant', 'Atelier JB', 'A step-cut aquamarine on a fine cable chain. Blue that reads green in daylight and holds still at night.', 'necklaces', 640000, NULL, array['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"1.8ct aquamarine"},{"label":"Metal","value":"18k yellow gold"},{"label":"Length","value":"42cm, adjustable to 45cm"},{"label":"Clasp","value":"Spring ring"}]'::jsonb, array['new']::text[], true, NULL, false, true, '2026-09-26T09:00:00Z'),
  ('3cbfc608-4bb8-4eb6-971c-e6049a5e981a', 'layered-chain-set', 'Layered Chain Set', 'Aster', 'Two chains at different lengths, spaced so they sit rather than tangle. Worn together, read as one piece.', 'necklaces', 340000, NULL, array['https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"None"},{"label":"Metal","value":"18k gold vermeil"},{"label":"Length","value":"40cm + 46cm"},{"label":"Clasp","value":"Lobster"}]'::jsonb, array['everyday']::text[], true, NULL, false, false, '2026-09-08T09:00:00Z'),
  ('cecfab6b-bdcd-4b92-a6a8-141cf04c9afd', 'brilliance-pendant', 'Brilliance Pendant', 'Atelier JB', 'A single moissanite on an almost invisible chain. More fire than diamond, chosen on purpose.', 'necklaces', 980000, NULL, array['https://images.unsplash.com/photo-1589128777073-263566ae5e4d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"1.5ct moissanite · D–F"},{"label":"Metal","value":"18k white gold"},{"label":"Length","value":"42cm"},{"label":"Clasp","value":"Spring ring"}]'::jsonb, array['moissanite']::text[], true, NULL, false, true, '2026-08-22T09:00:00Z'),
  ('0838e0ea-376b-4da9-8cbe-97f52121912d', 'heart-pendant', 'Petite Heart Pendant', 'Aster', 'Small enough to wear under a collar. The first serious piece most people are given.', 'necklaces', 290000, NULL, array['https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1600721391689-2564bb8055de?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"0.25ct pavé moissanite"},{"label":"Metal","value":"Sterling silver, rhodium"},{"label":"Length","value":"40cm"},{"label":"Clasp","value":"Spring ring"}]'::jsonb, array['gift', 'everyday']::text[], true, NULL, false, false, '2026-09-18T09:00:00Z'),
  ('5a5822db-8e0d-42ca-82f7-3dc3e346ba46', 'dynasty-collar', 'Dynasty Collar', 'Heirloom', 'A ceremonial collar in high-karat gold set with rubies. Made to order, and made once.', 'necklaces', 2800000, NULL, array['https://images.unsplash.com/photo-1626784215021-2e39ccf971cd?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Ruby · 24 stones"},{"label":"Metal","value":"22k yellow gold"},{"label":"Length","value":"38cm collar"},{"label":"Clasp","value":"Barrel, safety catch"}]'::jsonb, array['statement', 'limited']::text[], true, NULL, true, false, '2026-05-30T09:00:00Z'),
  ('070738eb-c4fe-4167-ba5b-5f50c9b69da6', 'sapphire-drop-earrings', 'Sapphire Drop Earrings', 'Atelier JB', 'Pear-cut sapphires below a diamond surround. They move when you do, which is the whole point.', 'earrings', 780000, NULL, array['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1595781572981-d63151b232ed?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"2 × 1.1ct blue sapphire"},{"label":"Metal","value":"18k white gold"},{"label":"Setting","value":"Pear halo, drop"},{"label":"Fitting","value":"Post and butterfly"}]'::jsonb, array['statement']::text[], true, NULL, false, false, '2026-08-02T09:00:00Z'),
  ('90b3307b-b214-4192-87cc-783948b67355', 'moissanite-studs', 'Moissanite Studs', 'Atelier JB', 'One carat each, four prongs, nothing else. The pair you stop taking off.', 'earrings', 450000, NULL, array['https://images.unsplash.com/photo-1595781572981-d63151b232ed?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"2 × 1.0ct moissanite · D–F"},{"label":"Metal","value":"18k white gold"},{"label":"Setting","value":"Four-prong"},{"label":"Fitting","value":"Screw-back post"}]'::jsonb, array['moissanite', 'everyday']::text[], true, NULL, false, true, '2026-09-22T09:00:00Z'),
  ('533549b4-7795-4a3e-afad-e7add1f88b07', 'gold-hoops', 'Classic Gold Hoops', 'Aster', 'Twenty millimetres, hollow so they stay light, polished so they stay bright.', 'earrings', 260000, NULL, array['https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"None"},{"label":"Metal","value":"18k yellow gold"},{"label":"Setting","value":"Hollow tube, 20mm"},{"label":"Fitting","value":"Hinged snap"}]'::jsonb, array['everyday', 'gift']::text[], true, NULL, false, false, '2026-09-06T09:00:00Z'),
  ('56c0ab0c-4f7b-48a5-8d8b-4c926406820a', 'azure-heart-drops', 'Azure Heart Drops', 'Aster', 'Faceted blue crystal hearts on a French wire. Two pairs left from the Valentine''s run.', 'earrings', 310000, NULL, array['https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1595781572981-d63151b232ed?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Blue topaz · heart cut"},{"label":"Metal","value":"Sterling silver"},{"label":"Setting","value":"Bezel drop"},{"label":"Fitting","value":"French wire"}]'::jsonb, array['gift', 'limited']::text[], true, 2, false, false, '2026-07-25T09:00:00Z'),
  ('62a34fda-6e26-453d-8992-0eb86fd12cbb', 'tennis-bracelet', 'Moissanite Tennis Bracelet', 'Atelier JB', 'Fifty stones in a continuous line, each set to catch light independently. Weight you notice.', 'bracelets', 1450000, NULL, array['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"50 × 0.1ct moissanite"},{"label":"Metal","value":"18k rose gold"},{"label":"Length","value":"18cm"},{"label":"Clasp","value":"Box with double catch"}]'::jsonb, array['moissanite', 'statement']::text[], true, NULL, false, true, '2026-09-14T09:00:00Z'),
  ('ac30916e-a680-4bcd-a9ca-6d74511f7c41', 'ice-link-bracelet', 'Ice Link Bracelet', 'Obsidian', 'Pavé links that read as solid until they move. Heavier than it looks, on purpose.', 'bracelets', 1150000, 1340000, array['https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Pavé moissanite"},{"label":"Metal","value":"18k white gold"},{"label":"Length","value":"19cm"},{"label":"Clasp","value":"Push-button box"}]'::jsonb, array['statement']::text[], true, NULL, false, false, '2026-06-28T09:00:00Z'),
  ('af924592-d015-4930-877a-375258460357', 'curb-chain-bracelet', 'Curb Chain Bracelet', 'Aster', 'A flat curb link that lies properly against the wrist. Unisex, and better for it.', 'bracelets', 480000, NULL, array['https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"None"},{"label":"Metal","value":"18k yellow gold"},{"label":"Length","value":"20cm"},{"label":"Clasp","value":"Lobster"}]'::jsonb, array['everyday']::text[], true, NULL, false, false, '2026-09-10T09:00:00Z'),
  ('2703fd9c-5cc0-4073-8809-312ac4f760ea', 'rose-charm-bracelet', 'Rose Charm Bracelet', 'Heirloom', 'Five charms on a rose gold chain, added to over years rather than bought at once.', 'bracelets', 390000, NULL, array['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"Mixed cabochons"},{"label":"Metal","value":"14k rose gold"},{"label":"Length","value":"18cm"},{"label":"Clasp","value":"Lobster with extender"}]'::jsonb, array['gift']::text[], true, NULL, false, false, '2026-08-18T09:00:00Z'),
  ('4b54d899-f9cd-4909-985e-b9da017924e7', 'gold-bangle-stack', 'Gold Bangle Stack', 'Heirloom', 'Four hollow bangles in high-karat gold. Between runs — the next batch is being cast.', 'bracelets', 720000, NULL, array['https://images.unsplash.com/photo-1611107683227-e9060eccd846?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1400&q=80', 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1400&q=80']::text[], '[{"label":"Stone","value":"None"},{"label":"Metal","value":"22k yellow gold"},{"label":"Length","value":"6.5cm inner diameter"},{"label":"Clasp","value":"None, slip-on"}]'::jsonb, array['statement']::text[], false, NULL, false, false, '2026-05-09T09:00:00Z')
on conflict (id) do nothing;

-- 19 variants across 7 pieces.
insert into public.product_variants (id, product_id, label, options, price_ngn, in_stock, position)
values
  ('6c972226-3daa-4435-9ef3-b2539ef0a12c', 'e38265ce-8879-4892-84f2-1a86e1307fde', 'Oxblood calf · 40mm', '{"strap":"Oxblood calf","size":"40mm"}'::jsonb, 1850000, true, 0),
  ('797e50d2-92a0-453d-aa14-e62f8f972c92', 'e38265ce-8879-4892-84f2-1a86e1307fde', 'Ivory calf · 40mm', '{"strap":"Ivory calf","size":"40mm"}'::jsonb, 1850000, true, 1),
  ('b967b728-aab9-4b87-9f9b-8063749d1661', 'e38265ce-8879-4892-84f2-1a86e1307fde', 'Steel bracelet · 40mm', '{"strap":"Steel bracelet","size":"40mm"}'::jsonb, 2030000, true, 2),
  ('ebe7bbc0-082b-471f-9f9c-e6baa1c845bf', '6e83221b-2272-4c93-a44d-f4423cd28d02', 'Brown calf · 41mm', '{"strap":"Brown calf","size":"41mm"}'::jsonb, 2450000, true, 0),
  ('9950e1eb-7038-4524-b767-f48baed507e2', '6e83221b-2272-4c93-a44d-f4423cd28d02', 'Black calf · 41mm', '{"strap":"Black calf","size":"41mm"}'::jsonb, 2450000, true, 1),
  ('2f7d3586-d983-4768-8317-eea51eabfeb5', '131945fd-6a11-410c-bfde-ee78fc085438', 'Steel bracelet · 42mm', '{"strap":"Steel bracelet","size":"42mm"}'::jsonb, 1650000, true, 0),
  ('62b10321-5693-48c9-bb1f-c097e6b042d2', '131945fd-6a11-410c-bfde-ee78fc085438', 'Black rubber · 42mm', '{"strap":"Black rubber","size":"42mm"}'::jsonb, 1530000, true, 1),
  ('682cc632-3316-4dc7-ac43-692623c43a13', '91c8cbfc-327e-423c-9bdd-5da8b5ead71c', 'Size M', '{"size":"M"}'::jsonb, 1200000, true, 0),
  ('ad463abf-bf72-42d9-9f22-15c3399ca40a', '91c8cbfc-327e-423c-9bdd-5da8b5ead71c', 'Size N', '{"size":"N"}'::jsonb, 1200000, true, 1),
  ('cca5384e-41da-40e4-bf21-face8a495cd6', '91c8cbfc-327e-423c-9bdd-5da8b5ead71c', 'Size O', '{"size":"O"}'::jsonb, 1200000, false, 2),
  ('ffd431d8-a78d-4b24-b7ca-97c536ab22cc', '91c8cbfc-327e-423c-9bdd-5da8b5ead71c', 'Size P', '{"size":"P"}'::jsonb, 1200000, true, 3),
  ('f3d4a771-5d3e-45cf-ad10-881478b79620', 'a5b1d9b1-1fda-4d8f-9ccc-670a93d0da2f', 'Size M', '{"size":"M"}'::jsonb, 860000, true, 0),
  ('59f48d67-2275-44c9-ace0-283dc3a53ebc', 'a5b1d9b1-1fda-4d8f-9ccc-670a93d0da2f', 'Size N', '{"size":"N"}'::jsonb, 860000, true, 1),
  ('9083e9f2-a337-4b34-88a4-ac59511d5166', 'a5b1d9b1-1fda-4d8f-9ccc-670a93d0da2f', 'Size O', '{"size":"O"}'::jsonb, 860000, true, 2),
  ('eb0f1514-2ad0-4db4-8bea-edeb779549e9', '308c4c91-0208-4511-8b39-9adb76a34a25', '42cm', '{"length":"42cm"}'::jsonb, 640000, true, 0),
  ('826d6f46-509b-4853-913c-1ae09b45e42d', '308c4c91-0208-4511-8b39-9adb76a34a25', '45cm', '{"length":"45cm"}'::jsonb, 665000, true, 1),
  ('223931f7-3a1c-4375-8799-accb2981fc51', '308c4c91-0208-4511-8b39-9adb76a34a25', '50cm', '{"length":"50cm"}'::jsonb, 685000, true, 2),
  ('01bded7c-e553-4572-a939-f0dc8e8dbeba', 'cecfab6b-bdcd-4b92-a6a8-141cf04c9afd', '42cm', '{"length":"42cm"}'::jsonb, 980000, true, 0),
  ('050c7c09-5e16-428c-9e68-9cd703fde00a', 'cecfab6b-bdcd-4b92-a6a8-141cf04c9afd', '45cm', '{"length":"45cm"}'::jsonb, 1010000, true, 1)
on conflict (id) do nothing;

-- 38 Lagos areas by dispatch rider, 35 states by air freight.
-- Zamfara is absent on purpose and Bayelsa is inactive, so both routes to a
-- null delivery fee are reachable.
insert into public.delivery_rates (id, mode, name, state, fee_ngn, active, position)
values
  ('c2e716ca-54b7-451d-8323-c36f257c1c43', 'dispatch', 'Agege', 'Lagos', 5000, true, 0),
  ('2d1e0aec-2e1d-4906-a8d1-32e7f006d77d', 'dispatch', 'Alimosho', 'Lagos', 5000, true, 1),
  ('dae43d5c-b77d-4f48-a339-e52a0359553f', 'dispatch', 'Amuwo-Odofin', 'Lagos', 5000, true, 2),
  ('325ad793-67e1-441b-8e71-28eb2cb8ccbd', 'dispatch', 'Apapa', 'Lagos', 5000, true, 3),
  ('41aa479a-3b92-4d12-a484-1d414bc7e75f', 'dispatch', 'Ebute Metta', 'Lagos', 5000, true, 4),
  ('4e60d561-3ea3-4bd5-ad9a-aaed557b4e36', 'dispatch', 'Egbeda', 'Lagos', 5000, true, 5),
  ('fad5cc8f-313b-4ad6-814a-d058f3a63fc7', 'dispatch', 'Ejigbo', 'Lagos', 5000, true, 6),
  ('6e7a62a6-0938-4ca8-9bd1-540f60f7b207', 'dispatch', 'Festac', 'Lagos', 5000, true, 7),
  ('40f41aed-7329-4e77-b1a9-cd2f81124cc4', 'dispatch', 'Gbagada', 'Lagos', 5000, true, 8),
  ('51c90ce8-398c-4ebc-92e6-e124a828d4df', 'dispatch', 'Ikeja', 'Lagos', 5000, true, 9),
  ('10d2e993-41e4-4080-bff8-d8f532a10b15', 'dispatch', 'Ilupeju', 'Lagos', 5000, true, 10),
  ('4ee2be2f-3ce2-4bb7-a56d-ed7b0c31c9d1', 'dispatch', 'Isolo', 'Lagos', 5000, true, 11),
  ('c7bc545e-831a-4c09-84f1-805bf7a40f9e', 'dispatch', 'Ketu', 'Lagos', 5000, true, 12),
  ('47acc0f6-15c2-4af9-bf59-4fb501b33ac4', 'dispatch', 'Maryland', 'Lagos', 5000, true, 13),
  ('97c40ad0-ea44-4d32-8b73-a0a97fa035f4', 'dispatch', 'Mushin', 'Lagos', 5000, true, 14),
  ('b38a30bb-7040-4d15-9119-6887686f2c6a', 'dispatch', 'Ogba', 'Lagos', 5000, true, 15),
  ('d2abe80c-a37a-4137-834b-5864097aa724', 'dispatch', 'Ogudu', 'Lagos', 5000, true, 16),
  ('f2409a7c-3587-4abf-8eb3-9368b9881d64', 'dispatch', 'Oshodi', 'Lagos', 5000, true, 17),
  ('6611b37c-df2f-4bb4-99f3-f2d5c4bd7315', 'dispatch', 'Shomolu', 'Lagos', 5000, true, 18),
  ('b1b2051b-6a24-46bf-a271-e3963a96e974', 'dispatch', 'Surulere', 'Lagos', 5000, true, 19),
  ('c1bd3eed-8594-4695-8f89-8ab56643d7ff', 'dispatch', 'Yaba', 'Lagos', 5000, true, 20),
  ('ae71426f-5344-4387-95ae-2ac08d685e08', 'dispatch', 'Banana Island', 'Lagos', 6500, true, 100),
  ('0628702a-dd8d-4136-b9ca-c6e84694109a', 'dispatch', 'Ikoyi', 'Lagos', 6500, true, 101),
  ('3f6d6323-b6dc-426b-8322-7ada6c152a8e', 'dispatch', 'Lagos Island', 'Lagos', 6500, true, 102),
  ('54a17a62-aeef-4b3e-8bce-82bbdee0f2b6', 'dispatch', 'Lekki Phase 1', 'Lagos', 6500, true, 103),
  ('2ce5d017-6732-406f-a328-31c77874049d', 'dispatch', 'Oniru', 'Lagos', 6500, true, 104),
  ('5cf51b8a-e801-488c-8f68-bbd927789596', 'dispatch', 'Victoria Island', 'Lagos', 6500, true, 105),
  ('3bd75cdd-ff64-4668-8c2c-be403b33352c', 'dispatch', 'Ajah', 'Lagos', 8000, true, 200),
  ('6268b31f-bba1-421b-9368-c8155ed7175f', 'dispatch', 'Awoyaya', 'Lagos', 8000, true, 201),
  ('383908b3-4895-452f-90df-c5e32ac9ba0c', 'dispatch', 'Chevron', 'Lagos', 8000, true, 202),
  ('e174ce55-236f-4907-b857-f7afbbd9e2c4', 'dispatch', 'Ibeju-Lekki', 'Lagos', 8000, true, 203),
  ('a03a77b2-d9b4-4eee-b5aa-fdcff2768046', 'dispatch', 'Ikate', 'Lagos', 8000, true, 204),
  ('58ad4781-4879-4992-b38a-e273b11d0d82', 'dispatch', 'Sangotedo', 'Lagos', 8000, true, 205),
  ('23b95b24-efe7-4e87-9b83-7fba2e1e22c8', 'dispatch', 'Badagry', 'Lagos', 10000, true, 300),
  ('75d347db-e99f-4276-bea1-3797ddbd2c6f', 'dispatch', 'Epe', 'Lagos', 10000, true, 301),
  ('4282056b-4277-46b9-9eb2-7afe32aab777', 'dispatch', 'Ikorodu', 'Lagos', 10000, true, 302),
  ('91625832-d11e-47ce-b17a-fea996525380', 'dispatch', 'Ojo', 'Lagos', 10000, true, 303),
  ('6836b9ef-2fc9-46a5-8957-cb505d66f20a', 'dispatch', 'Sango Ota', 'Lagos', 10000, true, 304),
  ('3cca6664-a322-4fd6-9d66-a828ef3044e5', 'flight', 'Abia', 'Abia', 16000, true, 0),
  ('fd9df989-61b1-45c3-be7b-fc039372534e', 'flight', 'Adamawa', 'Adamawa', 16000, true, 1),
  ('96ef3eff-20f6-4775-b8a1-1306278e2212', 'flight', 'Akwa Ibom', 'Akwa Ibom', 12000, true, 2),
  ('a9af2e48-8cff-4f9f-b3cc-ccec25e0fa73', 'flight', 'Anambra', 'Anambra', 12000, true, 3),
  ('ee23cbb0-99ef-4f19-9522-3477a2310cfc', 'flight', 'Bauchi', 'Bauchi', 16000, true, 4),
  ('9030ed5d-452d-423a-9c19-faf2a1662a7c', 'flight', 'Bayelsa', 'Bayelsa', 16000, false, 5),
  ('599d665b-eb0b-47d5-82f8-379cb37ea174', 'flight', 'Benue', 'Benue', 16000, true, 6),
  ('a4c48cda-eabb-4f96-a92f-aeb1e491bc2b', 'flight', 'Borno', 'Borno', 16000, true, 7),
  ('19bc4f58-0b35-44c8-b750-6402354b0ec4', 'flight', 'Cross River', 'Cross River', 16000, true, 8),
  ('be64b5c4-fe1d-4926-bfc8-48a3268f9a84', 'flight', 'Delta', 'Delta', 12000, true, 9),
  ('11a9957a-c055-4e27-9375-420021d9432e', 'flight', 'Ebonyi', 'Ebonyi', 16000, true, 10),
  ('e3c36a0b-ec9f-48d4-91f9-8fdbfca29503', 'flight', 'Edo', 'Edo', 12000, true, 11),
  ('48816906-928d-4c2b-81d3-1706e1bd4b9d', 'flight', 'Ekiti', 'Ekiti', 16000, true, 12),
  ('64a17ede-f7ac-4fd3-b58d-1d443a57e817', 'flight', 'Enugu', 'Enugu', 12000, true, 13),
  ('ac11e928-cc50-4033-9d36-34ea02d57752', 'flight', 'FCT (Abuja)', 'FCT (Abuja)', 12000, true, 14),
  ('312f3b55-0672-4a45-b7ce-6fcb96831879', 'flight', 'Gombe', 'Gombe', 16000, true, 15),
  ('69058e2a-9345-48e2-93b8-6b81de2f17d5', 'flight', 'Imo', 'Imo', 16000, true, 16),
  ('44987c6d-fe31-4e49-9049-268c2702beb7', 'flight', 'Jigawa', 'Jigawa', 16000, true, 17),
  ('68544450-c250-4c55-bab7-7da136434e41', 'flight', 'Kaduna', 'Kaduna', 12000, true, 18),
  ('1cfcd2f4-6f52-41df-b1f2-f88272a53392', 'flight', 'Kano', 'Kano', 12000, true, 19),
  ('86eee4a8-6e82-466a-896b-1022118ae3fd', 'flight', 'Katsina', 'Katsina', 16000, true, 20),
  ('8b8155f8-a991-4249-b0cd-67de1a883312', 'flight', 'Kebbi', 'Kebbi', 16000, true, 21),
  ('68d1aa6b-511a-4e15-b2de-5cbfbc6ad6c1', 'flight', 'Kogi', 'Kogi', 16000, true, 22),
  ('0c4db12c-ad28-4fac-b17e-4e3e65b404e5', 'flight', 'Kwara', 'Kwara', 16000, true, 23),
  ('28e3554e-cde3-4034-a6b7-72bbffe150dd', 'flight', 'Nasarawa', 'Nasarawa', 16000, true, 24),
  ('bfc340c5-7081-4b82-9f04-cdcb31e2dbe2', 'flight', 'Niger', 'Niger', 16000, true, 25),
  ('68878c89-68d8-46d3-ab1b-55ceea176898', 'flight', 'Ogun', 'Ogun', 16000, true, 26),
  ('827a8f67-5be3-49b2-8528-8ac99559082e', 'flight', 'Ondo', 'Ondo', 16000, true, 27),
  ('44287bcb-aedb-4cf2-b637-b8ab8fc6a150', 'flight', 'Osun', 'Osun', 16000, true, 28),
  ('cd0978bc-a635-4e01-9684-531c9be9d250', 'flight', 'Oyo', 'Oyo', 12000, true, 29),
  ('24b66807-8e1e-4e4a-9489-8b3d3a5bc2f7', 'flight', 'Plateau', 'Plateau', 16000, true, 30),
  ('0a76db9d-12d9-4f4f-8d0b-95bf957900c2', 'flight', 'Rivers', 'Rivers', 12000, true, 31),
  ('20cd8b80-521f-4792-8e18-3c412fc19d46', 'flight', 'Sokoto', 'Sokoto', 16000, true, 32),
  ('27a88965-6628-4fa9-8096-89407a119689', 'flight', 'Taraba', 'Taraba', 16000, true, 33),
  ('0050f351-d063-42af-8687-4021195fd3fc', 'flight', 'Yobe', 'Yobe', 16000, true, 34)
on conflict (id) do nothing;

-- The single-active trigger enforces that only one is_active row survives.
insert into public.announcements (id, message, is_active, created_at)
values
  ('e12bfe41-d5af-4e74-9cc6-dfcbb9c9d3b6', 'Complimentary insured delivery on orders above ₦1,000,000.', true, '2026-09-01T08:00:00Z'),
  ('6c916895-f3ea-41ef-8f93-da88801881b7', 'The Wedding Edit is open. Private viewings in Lekki by appointment.', false, '2026-07-14T08:00:00Z')
on conflict (id) do nothing;

-- Settings the app reads by key. `is_public` gates the read policy: only the
-- flagged rows are visible to anon, which is why the bank account is not one of
-- them — checkout gets it through the order-scoped get_payment_instructions()
-- RPC after an order exists, as PAYMENT_METHODS.bank_transfer.description
-- promises. Placeholders: set the real values in /admin/settings.
insert into public.site_settings (key, value, is_public) values
  -- STILL A PLACEHOLDER: the real account has not been supplied. Set it in
  -- /admin/settings before taking a bank transfer, or the confirmation email
  -- tells the customer to pay into nothing.
  ('bank_account', '{"bank_name":"Bank name","account_number":"0000000000","account_name":"JewelryBox"}'::jsonb, false),
  ('vendor_email', '"hello.jewelryboxng@gmail.com"'::jsonb, false),
  ('contact',      '{"email":"hello.jewelryboxng@gmail.com","phone":"+234 813 623 2942"}'::jsonb, true),
  -- E.164 digits only — no '+', no spaces. `wa.me/<number>` breaks on a space,
  -- and PublicSettings.whatsapp declares exactly this shape, so the seed matches
  -- the contract rather than the way a human writes a phone number. The display
  -- form lives in `contact.phone`.
  ('whatsapp',     '"2348136232942"'::jsonb, true),
  ('instagram',    '"https://www.instagram.com/stonegallery001"'::jsonb, true)
on conflict (key) do nothing;

-- Local convenience only, and deliberately not a schema feature: handle_new_user()
-- always writes 'customer', so there is no auto-promotion path to abuse and no
-- privileged email committed to git. In production this is one statement in the
-- SQL editor, once, at launch — see README.md.
--
-- No-op until someone has actually signed up locally with this address.
do $$
declare v_email text := coalesce(nullif(current_setting('jb.dev_admin_email', true), ''), 'admin@jewelrybox.test');
begin
  update public.profiles p
  set role = 'admin'
  from auth.users u
  where u.id = p.id and lower(u.email) = lower(v_email) and p.role <> 'admin';
  if found then
    raise notice 'Promoted % to admin.', v_email;
  else
    raise notice 'No local account for % yet — sign up, then re-run: npm run db:reset', v_email;
  end if;
end;
$$;
