// All 36 Nigerian states + FCT — used for delivery address selection.
export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT (Abuja)",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

// countriesnow.space has no city data for the FCT, so we keep a local list
// of its area councils and major districts.
export const FCT_CITIES = [
  "Abaji",
  "Asokoro",
  "Bwari",
  "Central Area",
  "Garki",
  "Gwagwalada",
  "Gwarinpa",
  "Jabi",
  "Karu",
  "Kubwa",
  "Kuje",
  "Kwali",
  "Lokogoma",
  "Lugbe",
  "Maitama",
  "Municipal Area Council (AMAC)",
  "Nyanya",
  "Utako",
  "Wuse",
] as const;
