/**
 * Generates `supabase/seed.sql` from the frontend lane's fixtures.
 *
 * `app/utils/mock/` is the single source of truth for the sample catalogue, so
 * the seed is derived rather than hand-maintained. Two copies of 28 products
 * would drift, and a drift there is exactly what the Phase F swap is supposed
 * to be invisible against: if the seeded database and the mock disagree, the
 * moment a composable switches repositories the page changes for reasons
 * nothing in the diff explains.
 *
 * IDs are deterministic — md5 of a stable key, shaped into a v4-looking uuid —
 * so `supabase db reset` never reshuffles them. That matters because wishlists,
 * recently-viewed and any hand-written test fixture reference products by id.
 *
 * LOCAL ONLY. The imagery is placeholder stock photography carried over from the
 * fixtures, and some of it shows other makers' trademarked product. Never load
 * this into a production database — `supabase db reset` is a local command, and
 * it should stay that way until real photography replaces the mock set at
 * Phase F, at which point regenerate rather than hand-editing.
 *
 * Run: npm run db:seed:generate    (then `npm run db:reset` to apply)
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { createJiti } from "jiti";

const ROOT = process.cwd();
const jiti = createJiti(ROOT + "/", {
  // The fixtures import through Nuxt's aliases, which a bare node run has no
  // idea about.
  alias: { "~": ROOT + "/app", "~~": ROOT },
});

/**
 * Stable uuid from a key. The version/variant nibbles are forced so the result
 * is a well-formed v4 rather than arbitrary hex in uuid shape — Postgres
 * accepts either, but a strict validator downstream would not.
 */
const uuid = (key) => {
  const h = createHash("md5").update(`jb:${key}`).digest("hex");
  const v = "4" + h.slice(13, 16);
  const r = ((parseInt(h[16], 16) & 0x3) | 0x8).toString(16) + h.slice(17, 20);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${v}-${r}-${h.slice(20, 32)}`;
};

/** Postgres string literal: double the quotes, never interpolate raw. */
const q = (v) => (v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const qArr = (xs) => `array[${xs.map(q).join(", ")}]::text[]`;
const qJson = (v) => `${q(JSON.stringify(v))}::jsonb`;
const bool = (v) => (v ? "true" : "false");
const num = (v) => (v === null || v === undefined ? "NULL" : String(v));

const { MOCK_PRODUCTS } = await jiti.import("./app/utils/mock/products.ts");
const { MOCK_RATES } = await jiti.import("./app/utils/mock/rates.ts");
const { MOCK_ANNOUNCEMENTS } = await jiti.import("./app/utils/mock/announcements.ts");

const productId = (p) => uuid(`product:${p.slug}`);
const variantId = (p, i) => uuid(`variant:${p.slug}:${i}`);
const rateId = (r) => uuid(`rate:${r.mode}:${r.name.toLowerCase()}`);

const out = [];
out.push(`-- Generated by scripts/generate-seed.mjs — DO NOT EDIT BY HAND.
--
-- LOCAL DEVELOPMENT ONLY. The imagery here is placeholder stock photography from
-- the fixtures and some of it shows other makers' trademarked product, so this
-- must never reach a production database. Replaced at Phase F by real
-- photography, at which point regenerate rather than editing.
--
-- Mirrors app/utils/mock/{products,rates,announcements}.ts so the Phase F swap
-- from fixtures to Supabase is invisible. Regenerate with:
--     npm run db:seed:generate
--
-- Deliberate holes preserved from the fixtures, because each one makes a real
-- code path reachable against the real database rather than only against mocks:
--   · Zamfara has no delivery_rates row at all  -> unpriced destination, null fee
--   · Bayelsa has a row but active = false      -> same path, different cause
--   · two pieces are out of stock               -> the sold_out raise
--   · two sit at stock_count = 2                -> the "2 left" low-stock badge
--   · three are made_to_order                   -> exempt from the sold_out check
--
-- Idempotent: every insert is ON CONFLICT DO NOTHING, and ids are deterministic
-- (md5 of a stable key), so re-running never duplicates or reshuffles a row.`);

/* ── products ─────────────────────────────────────────────────────────── */
out.push(`\n-- ${MOCK_PRODUCTS.length} pieces across all five categories.`);
out.push(
  `insert into public.products
  (id, slug, name, brand, description, category, price_ngn, compare_at_ngn,
   images, specs, tags, in_stock, stock_count, made_to_order, featured, created_at)
values`,
);
out.push(
  MOCK_PRODUCTS.map(
    (p) =>
      `  (${q(productId(p))}, ${q(p.slug)}, ${q(p.name)}, ${q(p.brand)}, ${q(p.description)}, ` +
      `${q(p.category)}, ${num(p.price_ngn)}, ${num(p.compare_at_ngn)}, ${qArr(p.images)}, ` +
      `${qJson(p.specs)}, ${qArr(p.tags)}, ${bool(p.in_stock)}, ${num(p.stock_count)}, ` +
      `${bool(p.made_to_order)}, ${bool(p.featured)}, ${q(p.created_at)})`,
  ).join(",\n") + "\non conflict (id) do nothing;",
);

/* ── product_variants ─────────────────────────────────────────────────── */
const variants = MOCK_PRODUCTS.flatMap((p) =>
  (p.variants ?? []).map((v, i) => ({ p, v, i })),
);
if (variants.length) {
  out.push(`\n-- ${variants.length} variants across ${new Set(variants.map((x) => x.p.slug)).size} pieces.`);
  out.push(
    `insert into public.product_variants (id, product_id, label, options, price_ngn, in_stock, position)
values`,
  );
  out.push(
    variants
      .map(
        ({ p, v, i }) =>
          `  (${q(variantId(p, i))}, ${q(productId(p))}, ${q(v.label)}, ${qJson(v.options)}, ` +
          `${num(v.price_ngn)}, ${bool(v.in_stock)}, ${num(v.position)})`,
      )
      .join(",\n") + "\non conflict (id) do nothing;",
  );
}

/* ── delivery_rates ───────────────────────────────────────────────────── */
const dispatch = MOCK_RATES.filter((r) => r.mode === "dispatch");
const flight = MOCK_RATES.filter((r) => r.mode === "flight");
out.push(
  `\n-- ${dispatch.length} Lagos areas by dispatch rider, ${flight.length} states by air freight.
-- Zamfara is absent on purpose and Bayelsa is inactive, so both routes to a
-- null delivery fee are reachable.`,
);
out.push(
  `insert into public.delivery_rates (id, mode, name, state, fee_ngn, active, position)
values`,
);
out.push(
  MOCK_RATES.map(
    (r) =>
      `  (${q(rateId(r))}, ${q(r.mode)}, ${q(r.name)}, ${q(r.state)}, ${num(r.fee_ngn)}, ` +
      `${bool(r.active)}, ${num(r.position)})`,
  ).join(",\n") + "\non conflict (id) do nothing;",
);

/* ── announcements ────────────────────────────────────────────────────── */
if (MOCK_ANNOUNCEMENTS.length) {
  out.push(`\n-- The single-active trigger enforces that only one is_active row survives.`);
  out.push(`insert into public.announcements (id, message, is_active, created_at)\nvalues`);
  out.push(
    MOCK_ANNOUNCEMENTS.map(
      (a) =>
        `  (${q(uuid(`announcement:${a.message}`))}, ${q(a.message)}, ${bool(a.is_active)}, ${q(a.created_at)})`,
    ).join(",\n") + "\non conflict (id) do nothing;",
  );
}

/* ── site_settings ────────────────────────────────────────────────────── */
out.push(`
-- Settings the app reads by key. \`is_public\` gates the read policy: only the
-- flagged rows are visible to anon, which is why the bank account is not one of
-- them — checkout gets it through the order-scoped get_payment_instructions()
-- RPC after an order exists, as PAYMENT_METHODS.bank_transfer.description
-- promises. Placeholders: set the real values in /admin/settings.
insert into public.site_settings (key, value, is_public) values
  ('bank_account', '{"bank_name":"Bank name","account_number":"0000000000","account_name":"JewelryBox"}'::jsonb, false),
  ('vendor_email', '"orders@jewelrybox.ng"'::jsonb, false),
  ('contact',      '{"email":"hello@jewelrybox.ng","phone":"+234 000 000 0000"}'::jsonb, true),
  ('whatsapp',     '"+2340000000000"'::jsonb, true)
on conflict (key) do nothing;`);

/* ── first admin ──────────────────────────────────────────────────────── */
out.push(`
-- Local convenience only, and deliberately not a schema feature: handle_new_user()
-- always writes 'customer', so there is no auto-promotion path to abuse and no
-- privileged email committed to git. In production this is one statement in the
-- SQL editor, once, at launch — see README.md.
--
-- No-op until someone has actually signed up locally with this address.
do $$
declare v_email text := coalesce(nullif(current_setting('jb.dev_admin_email', true), ''), 'admin@jewelrybox.test');
begin
  update public.profiles p
  set role = 'admin'
  from auth.users u
  where u.id = p.id and lower(u.email) = lower(v_email) and p.role <> 'admin';
  if found then
    raise notice 'Promoted % to admin.', v_email;
  else
    raise notice 'No local account for % yet — sign up, then re-run: npm run db:reset', v_email;
  end if;
end;
$$;`);

writeFileSync(`${ROOT}/supabase/seed.sql`, out.join("\n") + "\n");
console.log(
  `supabase/seed.sql written — ${MOCK_PRODUCTS.length} products, ${variants.length} variants, ` +
    `${MOCK_RATES.length} rates (${dispatch.length} dispatch / ${flight.length} flight), ` +
    `${MOCK_ANNOUNCEMENTS.length} announcement(s), 4 settings.`,
);
